import Head from 'next/head';
import React from 'react';
import { Button, Heading, Input } from '@chakra-ui/react';

function LoginPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="login">
        <main>
          <div className="login-form">
            <form action="">
              <Heading color={'#B0B0B0'} textAlign={'center'}>
                Kirish
              </Heading>
              <Input
                type="number"
                {...css.input}
                autoComplete="off"
                required
                placeholder="Sizning raqamingiz"
              />
              <Input
                {...css.input}
                type="password"
                required
                autoComplete="new-password"
                placeholder="Password"
              />
              <Button mt={'25px'} className="btn btn-primary" type="submit">
                Yuborish
              </Button>
            </form>
          </div>
        </main>
      </div>
    </>
  );
}

export default LoginPage;

const css = {
  input: {
    width: '100%',
    color: '#000',
    border: '2px solid #B0B0B0',
    backgroundColor: '#fff',
    borderRadius: '10px',
    transition: 'border-color 0.15s ease-in-out,box-shadow 0.15s ease-in-out',
    padding: '1rem 0.75rem',
    height: '50px',
    margin: '15px 0',

    _focus: {
      boxShadow: '0 0 0 .25rem rgba(254,93,55,0.25)',
      border: '2px solid #14151A',
      color: '#000'
    },

    _placeholder: {
      fontSize: '16px'
    }
  },
  image: {
    height: '100px',
    objectFit: 'cover',
    width: '100%'
  }
};
