import Head from 'next/head';
import React from 'react';
import Main from './components/Main';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Tabs, Tab, TabList, TabPanels, TabPanel, Box } from '@chakra-ui/react';
import ProfileAbout from './components/Profile';
import MyCourses from './components/MyCourses';

function Profile() {
  return (
    <>
      <Head>
        <title>buxgalter Pro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar />
      </nav>
      <main className="main">
        <Main />
        <Box className="container">
          <Tabs>
            <TabList>
              <Tab>Profile</Tab>
              <Tab>Kurslar</Tab>
            </TabList>
            <TabPanels>
              <TabPanel p={'0'}>
                <ProfileAbout />
              </TabPanel>
              <TabPanel p={'0'}>
                <MyCourses />
              </TabPanel>
            </TabPanels>
          </Tabs>
        </Box>
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  );
}

export default Profile;
