import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import { Box, Flex, Heading, Image, Text } from '@chakra-ui/react';
import Head from 'next/head';
import React from 'react';
import OneIcon from '@/assets/1.svg';
import Contents from '../_components/Contents';

function CourseAbout() {
  return (
    <>
      <Head>
        <title>buxgalter Pro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar />
      </nav>
      <main className="main">
        <Box p={'36px 0'}>
          <Box className="container">
            <Flex {...css.box}>
              <Heading {...css.name}>Бухгалтерия ҳисоби буйича дарслар</Heading>
              <Image src={OneIcon.src} alt="OneIcon" />
            </Flex>

            <Box {...css.bottom}>
              <Heading {...css.title}>Бухгалтерия ҳисоби буйича дарслар</Heading>
              <Text {...css.text}>
                Endi sizda buning uchun ajoyib imkoniyat bor. Al-Muamalat Education tomonidan taqdim
                etilgan Islom moliyasi savodxonligi kursi boshlanmoqda. Ushbu kursda quyidagi asosiy
                mavzular o`rganiladi: -Islom moliyasi nima: Islom moliyasining asosiy tushunchalari
                va qoidalari -Shartnomalar: Ularning turlari va qanday qo‘llanilishi -Takaful nima
                ekanligini va uning qanday ishlashi -Sukuk turlari va ularning moliyaviy
                mexanizmlari -Zakot hisoblash va kimlarga berilishi.
              </Text>
            </Box>

            <Contents />
          </Box>
        </Box>
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  );
}

export default CourseAbout;

const css = {
  name: {
    color: '#262626',
    fontSize: '32px',
    lineHeight: '38px',
    fontFamily: 'Inter, sans-serif'
  },
  box: {
    alignItems: 'center',
    gap: '16px',
    width: '100%',
    boxShadow: 'rgba(144, 173, 248, 0.25) 0px 9px 18px 0px',
    background: '#fff',
    height: '190px',
    padding: '24px',
    borderRadius: '16px',
    justifyContent: 'space-around'
  },
  bottom: {
    width: '100%',
    boxShadow: 'rgba(144, 173, 248, 0.25) 0px 9px 18px 0px',
    background: '#fff',
    padding: '24px',
    borderRadius: '16px',
    marginTop: '24px'
  },
  title: {
    color: '#262626',
    fontSize: '25px',
    lineHeight: '38px',
    fontFamily: 'Inter, sans-serif',
    marginBottom: '16px'
  },
  text: {
    color: '#74787c',
    fontSize: '16px',
    lineHeight: '24px',
    fontFamily: 'Inter, sans-serif'
  }
};
