import Head from 'next/head';
import localFont from 'next/font/local';
import Navbar from '@/components/Navbar';
import Courses from '@/components/Courses';
import Footer from '@/components/Footer';
import Services from '@/components/Services';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export default function Home() {
  return (
    <>
      <Head>
        <title>buxgalter Pro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <nav>
          {' '}
          <Navbar />
        </nav>
        <main className="main">
          <Services />
          <Courses />
        </main>
        <footer>
          <Footer />
        </footer>
      </>
    </>
  );
}
